export const codeSetsData = [
  {
    name: 'ICD10',
    codes: '70633',
    is_active: true,
    is_lock: true,
    index: 0,
  },
  {
    name: 'ICD9',
    codes: '70',
    is_active: true,
    is_lock: true,
    index: 1,
  },
  {
    name: 'SNOMED-CT',
    codes: '7',
    is_active: true,
    is_lock: false,
    index: 2,
  },
  {
    name: 'Custom Code Set',
    codes: '2',
    is_active: false,
    is_lock: false,
    index: 3,
  },
  {
    name: 'My Clinic Codes',
    codes: '5',
    is_active: false,
    is_lock: true,
    index: 4,
  },
]

export const codeData = [
  {
    code: '8293',
    layer1: 'Something',
    layer2: 'Surgery',
    layer3: 'Sinal',
    description: 'Spinal reconstruction',
    index: 0,
  },
  {
    code: '78445',
    layer1: 'ID',
    layer2: 'ID',
    layer3: 'ID',
    description: 'ID reconstruction',
    index: 1,
  },
  {
    code: '23',
    layer1: '',
    layer2: 'ICD10',
    layer3: '',
    description: 'test reconstruction',
    index: 2,
  },
  {
    code: '7',
    layer1: '',
    layer2: '',
    layer3: '',
    description: 'Spinal reconstruction',
    index: 3,
  },
  {
    code: '4514',
    layer1: '',
    layer2: 'AI',
    layer3: '',
    description: 'AI reconstruction',
    index: 4,
  },
  {
    code: '787878',
    layer1: '',
    layer2: 'IDT',
    layer3: '',
    description: 'IDT reconstruction',
    index: 5,
  },
  {
    code: '8989',
    layer1: 'ICD10',
    layer2: 'ICD10',
    layer3: 'ICD10',
    description: 'reconstruction',
    index: 6,
  },
  {
    code: 'ICD0',
    layer1: '',
    layer2: '',
    layer3: '',
    description: 'IDT',
    index: 7,
  },
]
