export const data = [
  {
    key: '1',
    name: 'Paracetamol (Acetominophen)',
    unit: 'Mg',
    frequency: '1 per day',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 1,
    index: 0,
  },
  {
    key: '2',
    name: 'From a friend',
    unit: 'Mg',
    frequency: 'coffee',
    route: 'Monday, 4 Feb 2019',
    comment: "Twice per 6 hours after treatment",
    is_active: 0,
    index: 1,
  },
  {
    key: '3',
    name: 'Instagram',
    unit: 'Mg',
    frequency: 'clock',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 0,
    index: 2,
  },
  {
    key: '4',
    name: 'Imported',
    unit: 'Mg',
    frequency: '1 per day',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 1,
    index: 3,
  },
  {
    key: '5',
    name: 'Walk-in',
    unit: "Mg",
    frequency: '1 per day',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 1,
    index: 4,
  },
  {
    key: '6',
    name: 'Facebook',
    unit: 'Mg',
    frequency: '1 per day',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 0,
    index: 5,
  },
  {
    key: '7',
    name: 'Fresha',
    unit: "Mg",
    frequency: '1 per day',
    route: 'Orally',
    comment: "Twice per 6 hours after treatment",
    is_active: 0,
    index: 6,
  },
]
