import { ShareAltOutlined, HomeOutlined, EditOutlined } from '@ant-design/icons'
export const defaultBuilderSetting = {
  appearance: {
    backgroundColor: 'strong',
    iconColor: '',
    headerColor: '',
    footerColor: '',
  },
  registrationFields: [
    {
      fieldName: 'Salutation',
      label: 'Salutation',
      visible: false,
      required: false,
      key: 1,
    },
    {
      fieldName: 'First Name',
      label: 'First Name',
      visible: true,
      required: true,
      disabled: true,
      key: 2,
    },
    {
      fieldName: 'Last Name',
      label: 'Last Name',
      visible: true,
      required: true,
      disabled: true,
      key: 3,
    },
    {
      fieldName: 'Gender',
      label: 'Gender',
      visible: false,
      required: false,
      key: 4,
    },
    {
      fieldName: 'Date of Birth',
      label: 'Date of Birth',
      visible: false,
      required: false,
      key: 5,
    },
    {
      fieldName: 'Mobile',
      label: 'Mobile',
      visible: false,
      required: false,
      key: 6,
    },
    {
      fieldName: 'Address',
      label: 'Address',
      visible: false,
      required: false,
      key: 7,
    },
    {
      fieldName: 'City',
      label: 'City',
      visible: false,
      required: false,
      key: 8,
    },
    {
      fieldName: 'Country',
      label: 'Country',
      visible: false,
      required: false,
      key: 9,
    },
    {
      fieldName: 'Post code',
      label: 'Post code',
      visible: false,
      required: false,
      key: 10,
    },
    {
      fieldName: 'How did you hear about us?',
      label: 'How did you hear about us?',
      visible: false,
      required: false,
      key: 11,
    },
  ],
  customFields: [
    {
      fieldName: 'GP Name',
      label: 'GP Name',
      visible: false,
      required: false,
      key: 1,
    },
    {
      fieldName: 'GP Address',
      label: 'GP Address',
      visible: false,
      required: false,
      key: 2,
    },
    {
      fieldName: 'Gender',
      label: 'Gender',
      visible: false,
      required: false,
      key: 3,
    },
    {
      fieldName: 'Test MC',
      label: 'Test MC',
      visible: false,
      required: false,
      key: 4,
    },
  ],
}

export const defaultStepData = [
  {
    step: 0,
    name: 'Basics',
    img: <HomeOutlined />,
    isActive: true,
    index: 0,
  },
  {
    step: 1,
    name: 'Widget',
    img: <EditOutlined />,
    isActive: false,
    index: 1,
  },
  {
    step: 2,
    name: 'Share',
    img: <ShareAltOutlined />,
    isActive: false,
    index: 2,
  },
]
