import austin from '../../../../../../libs/ui/src/assets/images/users/austin.png'
import james from '../../../../../../libs/ui/src/assets/images/users/james.png'
import linda from '../../../../../../libs/ui/src/assets/images/users/linda.png'
import arya from '../../../../../../libs/ui/src/assets/images/users/arya.png'
import alex from '../../../../../../libs/ui/src/assets/images/users/alex.png'

export const mockUsers = [
  //TODO Remove once users endpoints are implemented
  {
    id: 1,
    name: 'Joseph',
    surname: 'Howard',
    title: 'Managing Director',
    img: austin,
    vacationPending: true,
    available: true,
    active: true,
  },
  {
    id: 2,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: alex,
    vacationPending: false,
    available: true,
    active: true,
  },
  {
    id: 3,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: arya,
    active: false,
    vacationPending: false,
    available: true,
  },
  {
    id: 4,
    name: 'Joseph',
    surname: 'Howard',
    title: 'Managing Director',
    vacationPending: false,
    available: true,
    active: true,
    img: james,
  },
  {
    id: 5,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: austin,
    active: true,
  },
  {
    id: 6,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: arya,
    active: false,
    vacationPending: false,
    available: true,
  },
  {
    id: 7,
    name: 'Joseph',
    surname: 'Howard',
    title: 'Managing Director',
    vacationPending: false,
    available: true,
    active: false,
    img: austin,
  },
  {
    id: 8,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: james,
    active: true,
  },
  {
    id: 9,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: arya,
    active: false,
    vacationPending: true,
    available: false,
  },
  {
    id: 10,
    name: 'Joseph',
    surname: 'Howard',
    title: 'Managing Director',
    vacationPending: false,
    available: true,
    active: true,
    img: austin,
  },
  {
    id: 11,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: austin,
    active: true,
  },
  {
    id: 22,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: linda,
    active: false,
    vacationPending: false,
    available: true,
  },
  {
    id: 23,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: austin,
    active: true,
  },
  {
    id: 24,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: arya,
    active: false,
    vacationPending: true,
    available: false,
  },
  {
    id: 25,
    name: 'Andrew',
    surname: 'Davis',
    title: 'Aesthetician',
    img: austin,
    active: true,
  },
  {
    id: 26,
    name: 'Frances',
    surname: 'Butler',
    title: 'Manager',
    img: alex,
    active: false,
    vacationPending: true,
    available: false,
  },
]
