export const dataSource = [
  {
    key: 0,
    desc: 'PAYROLL',
    type: 'header',
    header_num: 0,
  },
  {
    key: 1,
    desc: 'Team Comission',
    'name-1': '£ 100,000.00',
    'name-2': '£ 100,000.00',
    'name-3': '£ 100,000.00',
    'name-4': '£ 100,000.00',
    total: '£ 100,000.00',
  },
  {
    key: 2,
    desc: 'Team Wages',
    'name-1': '£ 3,500.00',
    'name-2': '£ 3,500.00',
    'name-3': '£ 3,500.00',
    'name-4': '£ 3,500.00',
    total: '£ 3,500.00',
  },
  {
    key: 3,
    desc: 'Total',
    'name-1': '£ 3,500.00',
    'name-2': '£ 3,500.00',
    'name-3': '£ 3,500.00',
    'name-4': '£ 3,500.00',
    total: '£ 3,500.00',
    type: 'summary',
  },
  {
    key: 4,
    desc: 'SHIFTS',
    type: 'header',
    header_num: 1,
  },
  {
    key: 5,
    desc: 'Days Worked',
    'name-1': {
      value: '18',
      badge: 'success',
    },
    'name-2': {
      value: '18',
      badge: 'success',
    },
    'name-3': {
      value: '18',
      badge: 'success',
    },
    'name-4': {
      value: '18',
      badge: 'success',
    },
    total: {
      value: '18',
      badge: 'success',
    },
  },
  {
    key: 6,
    desc: 'Days Off',
    'name-1': {
      value: '8',
      badge: 'error',
    },
    'name-2': {
      value: '8',
      badge: 'error',
    },
    'name-3': {
      value: '8',
      badge: 'error',
    },
    'name-4': {
      value: '8',
      badge: 'error',
    },
    total: {
      value: '8',
      badge: 'error',
    },
    children: [
      {
        key: 7,
        desc: 'Day Off',
        'name-1': '8',
        'name-2': '8',
        'name-3': '8',
        'name-4': '8',
        total: '32',
      },
      {
        key: 8,
        desc: 'Holiday',
        'name-1': '3',
        'name-2': '3',
        'name-3': '3',
        'name-4': '3',
        total: '12',
      },
      {
        key: 9,
        desc: 'Sick Day',
        'name-1': '1',
        'name-2': '1',
        'name-3': '1',
        'name-4': '1',
        total: '4',
      },
    ],
  },
  {
    key: 10,
    desc: 'PERFORMANCE',
    type: 'header',
    header_num: 2,
  },
  {
    key: 11,
    desc: 'Services',
    'name-1': {
      value: '8',
      badge: 'error',
    },
    'name-2': {
      value: '8',
      badge: 'error',
    },
    'name-3': {
      value: '8',
      badge: 'error',
    },
    'name-4': {
      value: '8',
      badge: 'error',
    },
    total: {
      value: '8',
      badge: 'error',
    },
    children: [
      {
        key: 12,
        desc: 'Injectables',
        'name-1': '8',
        'name-2': '8',
        'name-3': '8',
        'name-4': '8',
        total: '32',
      },
      {
        key: 13,
        desc: 'Consultations',
        'name-1': '3',
        'name-2': '3',
        'name-3': '3',
        'name-4': '3',
        total: '12',
      },
      {
        key: 14,
        desc: 'Laser',
        'name-1': '1',
        'name-2': '1',
        'name-3': '1',
        'name-4': '1',
        total: '4',
        children: [
          {
            key: 15,
            desc: 'LHR - Back',
            'name-1': '8',
            'name-2': '8',
            'name-3': '8',
            'name-4': '8',
            total: '32',
          },
          {
            key: 16,
            desc: 'LHR - Front',
            'name-1': '3',
            'name-2': '3',
            'name-3': '3',
            'name-4': '3',
            total: '12',
          },
          {
            key: 17,
            desc: 'LHR - Small',
            'name-1': '1',
            'name-2': '1',
            'name-3': '1',
            'name-4': '1',
            total: '4',
          },
        ],
      },
    ],
  },
]

export const columns = [
  {
    title: '',
    dataIndex: 'desc',
    key: 'desc',
    fixed: 'left',
    align: 'left',
  },
  {
    title: 'William Brandham',
    dataIndex: 'name-1',
    key: 'name-1',
    align: 'right',
  },
  {
    title: 'Kate Pipson',
    dataIndex: 'name-2',
    key: 'name-2',
    align: 'right',
  },
  {
    title: 'William Brandham',
    dataIndex: 'name-3',
    key: 'name-3',
    align: 'right',
  },
  {
    title: 'Kate Pipson',
    dataIndex: 'name-4',
    key: 'name-4',
    align: 'right',
  },
  {
    title: 'Total',
    dataIndex: 'total',
    key: 'total',
    align: 'right',
  },
]
